wise-logger:
    image: ymian/wise-logger
    volumes:
      - /etc/hostname:/etc/hostname
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "ETCD_POINT=http://172.17.0.3:4001"
      - "DOCKERAPI_VERSION=1.24"
    labels:
      io.rancher.sidekicks: "logstash"
logstash:
    image: logstash:2
    net: "service:wise-logger"
    volumes_from:
      - wise-logger
    volumes:
      - /var/lib/docker/volumes:/logs
      - /var/log:/var/host/log
    command: [bash, -c, "logstash -f /tmp/conf.d --auto-reload"]
